apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx:alpine
    name: nginx
    resources: {}
    volumeMounts:
      - mountPath: /var/www/html
        name: vol1
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: vol1
      persistentVolumeClaim:
        claimName: local-pvc
status: {}