apiVersion: apps/v1
kind: ReplicaSet

metadata:
  name: my-app-replicaset
  labels:
    app: my-app
    tier: frontend
spec:
  template:
    metadata:
      name: my-app-pod
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
